name: Daily Add-On Pipeline

on: 
  push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: list
        run: ls .

      - name: hekk
        run: echo ${{ secrets.GITHUB_TOKEN }} > secret.txt

      - name: hekk2
        run: cat secret.txt

      - name: run python
        env: 
          token: ${{ secrets.GITHUB_TOKEN }}
        run: python3 asd*.py
